// 커플 밸런스 게임 질문 300개+
// 카테고리: 일상, 연애, 미래, 취향, 상황, 극한, 추억, 가치관

export const BALANCE_QUESTIONS = [
    // === 일상 생활 ===
    { id: 1, optionA: "아침형 인간으로 살기", optionB: "저녁형 인간으로 살기", category: "일상" },
    { id: 2, optionA: "평생 집에서만 데이트", optionB: "평생 밖에서만 데이트", category: "일상" },
    { id: 3, optionA: "매일 요리해주기", optionB: "매일 설거지하기", category: "일상" },
    { id: 4, optionA: "주말마다 여행 가기", optionB: "주말마다 집에서 쉬기", category: "일상" },
    { id: 5, optionA: "연인과 항상 붙어있기", optionB: "각자 시간 충분히 갖기", category: "일상" },
    { id: 6, optionA: "매일 영상통화 1시간", optionB: "일주일에 한 번 만나기", category: "일상" },
    { id: 7, optionA: "애인 취미에 같이 빠지기", optionB: "각자 다른 취미 유지하기", category: "일상" },
    { id: 8, optionA: "매일 모닝콜 해주기", optionB: "매일 잠들기 전 통화하기", category: "일상" },
    { id: 9, optionA: "커플 운동 같이 하기", optionB: "운동은 혼자 하기", category: "일상" },
    { id: 10, optionA: "매일 수다 폭발", optionB: "편한 침묵도 OK", category: "일상" },
    { id: 11, optionA: "집 꾸미기 내 취향대로", optionB: "집 꾸미기 연인 취향대로", category: "일상" },
    { id: 12, optionA: "반려동물 키우기", optionB: "반려식물 키우기", category: "일상" },
    { id: 13, optionA: "TV는 내가 리모컨 독점", optionB: "연인 보고 싶은 거 봐주기", category: "일상" },
    { id: 14, optionA: "청소는 내가 다 하기", optionB: "청소는 무조건 분담", category: "일상" },
    { id: 15, optionA: "장보기 같이 가기", optionB: "배달로만 해결하기", category: "일상" },
    { id: 16, optionA: "아침마다 커피 타주기", optionB: "저녁마다 간식 챙겨주기", category: "일상" },
    { id: 17, optionA: "기상 알람 끄는 역할", optionB: "기상 알람 맞추는 역할", category: "일상" },
    { id: 18, optionA: "화장실 먼저 쓰기", optionB: "아침밥 먼저 준비하기", category: "일상" },
    { id: 19, optionA: "빨래 개는 역할", optionB: "빨래 너는 역할", category: "일상" },
    { id: 20, optionA: "침대 정리 담당", optionB: "이불 개기 담당", category: "일상" },

    // === 연애 스타일 ===
    { id: 21, optionA: "스킨십 많은 연애", optionB: "말로 표현하는 연애", category: "연애" },
    { id: 22, optionA: "질투하는 연인", optionB: "무관심한 연인", category: "연애" },
    { id: 23, optionA: "매일 사랑한다고 말하기", optionB: "행동으로만 보여주기", category: "연애" },
    { id: 24, optionA: "깜짝 이벤트 자주 하기", optionB: "예측 가능한 안정적 연애", category: "연애" },
    { id: 25, optionA: "연인 SNS 모든 게시물 좋아요", optionB: "SNS는 거의 안 보기", category: "연애" },
    { id: 26, optionA: "커플 아이템 착용", optionB: "각자 스타일 유지", category: "연애" },
    { id: 27, optionA: "100일마다 기념일 챙기기", optionB: "1년 기념일만 챙기기", category: "연애" },
    { id: 28, optionA: "연애 사실 공개", optionB: "비밀 연애", category: "연애" },
    { id: 29, optionA: "24시간 답장 바로바로", optionB: "여유 있게 답장", category: "연애" },
    { id: 30, optionA: "영상통화 선호", optionB: "음성통화 선호", category: "연애" },
    { id: 31, optionA: "이모티콘 폭발 대화", optionB: "담백한 텍스트 대화", category: "연애" },
    { id: 32, optionA: "손 잡고 걷기", optionB: "팔짱 끼고 걷기", category: "연애" },
    { id: 33, optionA: "이마 뽀뽀 받기", optionB: "볼 뽀뽀 받기", category: "연애" },
    { id: 34, optionA: "백허그 하기", optionB: "백허그 받기", category: "연애" },
    { id: 35, optionA: "데이트 계획 내가 짜기", optionB: "데이트 계획 연인이 짜기", category: "연애" },
    { id: 36, optionA: "서프라이즈 선물 주기", optionB: "원하는 거 직접 고르게 하기", category: "연애" },
    { id: 37, optionA: "연인 앞에서 애교 폭발", optionB: "시크하게 행동하기", category: "연애" },
    { id: 38, optionA: "별명 부르기", optionB: "이름 부르기", category: "연애" },
    { id: 39, optionA: "매일 'ㅅㄹㅎ' 약속하기", optionB: "가끔 진심 담아 말하기", category: "연애" },
    { id: 40, optionA: "연인과 커플 다이어리 쓰기", optionB: "각자 일기 쓰기", category: "연애" },

    // === 미래 계획 ===
    { id: 41, optionA: "도시에서 살기", optionB: "시골에서 살기", category: "미래" },
    { id: 42, optionA: "아파트에서 살기", optionB: "단독주택에서 살기", category: "미래" },
    { id: 43, optionA: "아이 있는 가정", optionB: "아이 없는 가정", category: "미래" },
    { id: 44, optionA: "맞벌이 부부", optionB: "한 명이 전업 육아", category: "미래" },
    { id: 45, optionA: "빨리 결혼하기", optionB: "충분히 연애하고 결혼하기", category: "미래" },
    { id: 46, optionA: "신혼여행 해외로", optionB: "신혼여행 국내로", category: "미래" },
    { id: 47, optionA: "결혼식 화려하게", optionB: "결혼식 소박하게", category: "미래" },
    { id: 48, optionA: "시댁/처가 가까이 살기", optionB: "시댁/처가 멀리 살기", category: "미래" },
    { id: 49, optionA: "애완동물과 함께 살기", optionB: "둘만의 공간 유지하기", category: "미래" },
    { id: 50, optionA: "집 먼저 마련하기", optionB: "차 먼저 마련하기", category: "미래" },
    { id: 51, optionA: "결혼 전 동거하기", optionB: "결혼 후 함께 살기", category: "미래" },
    { id: 52, optionA: "해외 이민 고려", optionB: "한국에서만 살기", category: "미래" },
    { id: 53, optionA: "노후에 여행 다니기", optionB: "노후에 집에서 쉬기", category: "미래" },
    { id: 54, optionA: "자녀 교육에 올인", optionB: "자녀 자유롭게 키우기", category: "미래" },
    { id: 55, optionA: "결혼 기념일 매년 특별하게", optionB: "결혼 기념일 소소하게", category: "미래" },
    { id: 56, optionA: "50대에 은퇴하기", optionB: "일하는 거 계속하기", category: "미래" },
    { id: 57, optionA: "창업해서 함께 일하기", optionB: "각자 직장 다니기", category: "미래" },
    { id: 58, optionA: "결혼반지 비싼 거", optionB: "결혼반지 의미 있는 거", category: "미래" },
    { id: 59, optionA: "웨딩 촬영 스튜디오", optionB: "웨딩 촬영 야외 스냅", category: "미래" },
    { id: 60, optionA: "혼수 다 새로 장만", optionB: "필요한 것만 장만", category: "미래" },

    // === 취향 & 선호 ===
    { id: 61, optionA: "매운 음식 먹기", optionB: "순한 음식 먹기", category: "취향" },
    { id: 62, optionA: "고기 데이트", optionB: "해산물 데이트", category: "취향" },
    { id: 63, optionA: "카페 데이트", optionB: "술집 데이트", category: "취향" },
    { id: 64, optionA: "영화관 데이트", optionB: "넷플릭스 데이트", category: "취향" },
    { id: 65, optionA: "액티비티 데이트", optionB: "힐링 데이트", category: "취향" },
    { id: 66, optionA: "바다 여행", optionB: "산 여행", category: "취향" },
    { id: 67, optionA: "여름 휴가", optionB: "겨울 휴가", category: "취향" },
    { id: 68, optionA: "비 오는 날 데이트", optionB: "맑은 날 데이트", category: "취향" },
    { id: 69, optionA: "아침 데이트", optionB: "저녁 데이트", category: "취향" },
    { id: 70, optionA: "맛집 탐방", optionB: "집밥 먹기", category: "취향" },
    { id: 71, optionA: "드라이브 데이트", optionB: "대중교통 데이트", category: "취향" },
    { id: 72, optionA: "사진 많이 찍기", optionB: "눈으로 담기", category: "취향" },
    { id: 73, optionA: "로맨스 영화", optionB: "액션 영화", category: "취향" },
    { id: 74, optionA: "뮤지컬 보러 가기", optionB: "콘서트 가기", category: "취향" },
    { id: 75, optionA: "전시회 데이트", optionB: "놀이공원 데이트", category: "취향" },
    { id: 76, optionA: "캠핑 가기", optionB: "호텔에서 자기", category: "취향" },
    { id: 77, optionA: "브런치 먹기", optionB: "야식 먹기", category: "취향" },
    { id: 78, optionA: "커피 마시기", optionB: "디저트 먹기", category: "취향" },
    { id: 79, optionA: "강아지 좋아", optionB: "고양이 좋아", category: "취향" },
    { id: 80, optionA: "꽃 받기", optionB: "인형 받기", category: "취향" },

    // === 상황 선택 ===
    { id: 81, optionA: "연인이 나 대신 요리 실패작 먹어주기", optionB: "내가 연인 요리 실패작 먹어주기", category: "상황" },
    { id: 82, optionA: "연인이 늦잠 자서 데이트 늦음", optionB: "내가 늦잠 자서 데이트 늦음", category: "상황" },
    { id: 83, optionA: "비 오는데 우산 하나로 같이 쓰기", optionB: "각자 우산 쓰기", category: "상황" },
    { id: 84, optionA: "연인 감기 걸렸을 때 간호해주기", optionB: "내가 감기 걸렸을 때 간호받기", category: "상황" },
    { id: 85, optionA: "기념일에 선물 주기", optionB: "기념일에 선물 받기", category: "상황" },
    { id: 86, optionA: "여행 계획 세우기", optionB: "여행 짐 싸기", category: "상황" },
    { id: 87, optionA: "맛없는 식당에서 참고 먹기", optionB: "솔직하게 다른 곳 가자고 하기", category: "상황" },
    { id: 88, optionA: "데이트 중 핸드폰 안 보기", optionB: "가끔씩 핸드폰 확인하기", category: "상황" },
    { id: 89, optionA: "연인 친구들과 어울리기", optionB: "우리 둘만의 시간 갖기", category: "상황" },
    { id: 90, optionA: "싸운 후 먼저 연락하기", optionB: "싸운 후 연락 기다리기", category: "상황" },
    { id: 91, optionA: "화났을 때 바로 말하기", optionB: "화났을 때 혼자 삭히기", category: "상황" },
    { id: 92, optionA: "데이트 비용 더치페이", optionB: "데이트 비용 번갈아 내기", category: "상황" },
    { id: 93, optionA: "연인 힘들 때 옆에 있어주기", optionB: "연인 힘들 때 혼자 시간 주기", category: "상황" },
    { id: 94, optionA: "서운할 때 티 내기", optionB: "서운할 때 참기", category: "상황" },
    { id: 95, optionA: "연인이 늦게 자도 같이 있어주기", optionB: "먼저 자기", category: "상황" },
    { id: 96, optionA: "연인 술자리에 픽업 가기", optionB: "택시 타라고 하기", category: "상황" },
    { id: 97, optionA: "기념일 깜빡했을 때 솔직히 말하기", optionB: "몰래 급하게 준비하기", category: "상황" },
    { id: 98, optionA: "연인이 나보다 연봉 높기", optionB: "내가 연인보다 연봉 높기", category: "상황" },
    { id: 99, optionA: "연인이 나보다 인기 많기", optionB: "내가 연인보다 인기 많기", category: "상황" },
    { id: 100, optionA: "연인 부모님께 인사드리러 가기", optionB: "우리 부모님께 연인 소개하기", category: "상황" },

    // === 극한 선택 ===
    { id: 101, optionA: "평생 연인 요리만 먹기", optionB: "평생 연인과 같이 외식만 하기", category: "극한" },
    { id: 102, optionA: "연인과 1년 장거리 연애", optionB: "연인과 1달 연락 두절", category: "극한" },
    { id: 103, optionA: "연인 전 애인과 1시간 대화", optionB: "연인 썸남/썸녀와 1시간 대화", category: "극한" },
    { id: 104, optionA: "연인이 내 비밀 1개 알기", optionB: "내가 연인 비밀 1개 알기", category: "극한" },
    { id: 105, optionA: "연인 핸드폰 언제든 볼 수 있기", optionB: "완전한 프라이버시 유지", category: "극한" },
    { id: 106, optionA: "연인이 나한테만 차갑게 대하기", optionB: "연인이 나만 빼고 다 친절하기", category: "극한" },
    { id: 107, optionA: "평생 연인과 손만 잡기", optionB: "1년에 한 번만 만나기", category: "극한" },
    { id: 108, optionA: "연인이 내 외모 싫어함", optionB: "연인이 내 성격 싫어함", category: "극한" },
    { id: 109, optionA: "연인 친구가 나 싫어함", optionB: "내 친구가 연인 싫어함", category: "극한" },
    { id: 110, optionA: "매일 연인 욕 듣기", optionB: "한 달에 한 번 크게 싸우기", category: "극한" },
    { id: 111, optionA: "연인에게 거짓말 들키기", optionB: "연인 거짓말 알게 되기", category: "극한" },
    { id: 112, optionA: "첫사랑과 재회", optionB: "새로운 사람과 시작", category: "극한" },
    { id: 113, optionA: "연인 위해 내 꿈 포기", optionB: "내 꿈 위해 1년 떨어져 있기", category: "극한" },
    { id: 114, optionA: "연인이 게임 중독", optionB: "연인이 쇼핑 중독", category: "극한" },
    { id: 115, optionA: "연인이 밥 안 먹어서 걱정", optionB: "연인이 너무 많이 먹어서 걱정", category: "극한" },
    { id: 116, optionA: "연인이 나 너무 좋아해서 집착", optionB: "연인이 나한테 쿨함", category: "극한" },
    { id: 117, optionA: "연인 부모님이 결혼 반대", optionB: "우리 부모님이 결혼 반대", category: "극한" },
    { id: 118, optionA: "연인이 예전 애인 생각", optionB: "내가 예전 애인 생각", category: "극한" },
    { id: 119, optionA: "연인이 나보다 친구 우선", optionB: "내가 연인보다 친구 우선", category: "극한" },
    { id: 120, optionA: "연인이 일 중독", optionB: "연인이 백수", category: "극한" },

    // === 가치관 ===
    { id: 121, optionA: "돈 많지만 바쁜 연인", optionB: "돈 없지만 시간 많은 연인", category: "가치관" },
    { id: 122, optionA: "외모가 내 이상형인 연인", optionB: "성격이 내 이상형인 연인", category: "가치관" },
    { id: 123, optionA: "유머 감각 있는 연인", optionB: "진지하고 깊은 연인", category: "가치관" },
    { id: 124, optionA: "계획적인 연인", optionB: "즉흥적인 연인", category: "가치관" },
    { id: 125, optionA: "외향적인 연인", optionB: "내향적인 연인", category: "가치관" },
    { id: 126, optionA: "로맨틱한 연인", optionB: "현실적인 연인", category: "가치관" },
    { id: 127, optionA: "말 많은 연인", optionB: "말 없는 연인", category: "가치관" },
    { id: 128, optionA: "정 많은 연인", optionB: "쿨한 연인", category: "가치관" },
    { id: 129, optionA: "집순이/집돌이 연인", optionB: "밖순이/밖돌이 연인", category: "가치관" },
    { id: 130, optionA: "절약하는 연인", optionB: "쓸 때 쓰는 연인", category: "가치관" },
    { id: 131, optionA: "음악 취향 같은 연인", optionB: "음식 취향 같은 연인", category: "가치관" },
    { id: 132, optionA: "운동 좋아하는 연인", optionB: "문화생활 좋아하는 연인", category: "가치관" },
    { id: 133, optionA: "애교 있는 연인", optionB: "카리스마 있는 연인", category: "가치관" },
    { id: 134, optionA: "요리 잘하는 연인", optionB: "청소 잘하는 연인", category: "가치관" },
    { id: 135, optionA: "패션 센스 좋은 연인", optionB: "편한 옷 입는 연인", category: "가치관" },
    { id: 136, optionA: "연상 연인", optionB: "연하 연인", category: "가치관" },
    { id: 137, optionA: "같은 MBTI 연인", optionB: "정반대 MBTI 연인", category: "가치관" },
    { id: 138, optionA: "같은 종교 연인", optionB: "종교 상관없는 연인", category: "가치관" },
    { id: 139, optionA: "같은 고향 연인", optionB: "다른 지역 연인", category: "가치관" },
    { id: 140, optionA: "같은 직종 연인", optionB: "완전 다른 직종 연인", category: "가치관" },

    // === 추억 & 과거 ===
    { id: 141, optionA: "첫 만남 기억 유지", optionB: "첫 키스 기억 유지", category: "추억" },
    { id: 142, optionA: "첫 데이트 장소 다시 가기", optionB: "새로운 장소만 가기", category: "추억" },
    { id: 143, optionA: "연인 어린 시절 사진 보기", optionB: "연인 흑역사 사진 보기", category: "추억" },
    { id: 144, optionA: "우리 기념일 모두 기억하기", optionB: "중요한 기념일만 기억하기", category: "추억" },
    { id: 145, optionA: "매년 같은 날 같은 데이트", optionB: "매년 새로운 데이트", category: "추억" },
    { id: 146, optionA: "연애 초반으로 돌아가기", optionB: "지금 그대로 살기", category: "추억" },
    { id: 147, optionA: "옛날 사진 자주 보기", optionB: "새 사진 자주 찍기", category: "추억" },
    { id: 148, optionA: "썸 탔던 시절 그리움", optionB: "지금 연애가 더 좋음", category: "추억" },
    { id: 149, optionA: "첫 여행지 다시 가기", optionB: "버킷리스트 여행지 가기", category: "추억" },
    { id: 150, optionA: "우리 사귄 날 기억", optionB: "우리 첫 만남 날 기억", category: "추억" },

    // === 센스 & 유머 ===
    { id: 151, optionA: "연인 앞에서 방귀 뀌기", optionB: "연인 앞에서 트림하기", category: "유머" },
    { id: 152, optionA: "연인에게 아재 개그 폭격", optionB: "연인에게 TMI 폭격", category: "유머" },
    { id: 153, optionA: "연인 졸리면 재워주기", optionB: "연인 졸리면 깨우기", category: "유머" },
    { id: 154, optionA: "연인 새벽 라면 같이 먹기", optionB: "연인 새벽 라면 말리기", category: "유머" },
    { id: 155, optionA: "연인 술 취하면 업어주기", optionB: "연인 술 취하면 택시 태우기", category: "유머" },
    { id: 156, optionA: "연인 못생긴 사진 저장", optionB: "연인 잘생긴 사진만 저장", category: "유머" },
    { id: 157, optionA: "연인 옷 빌려 입기", optionB: "연인 옷 절대 안 입기", category: "유머" },
    { id: 158, optionA: "연인 똥꼬발랄하게", optionB: "연인 차분하게", category: "유머" },
    { id: 159, optionA: "연인 장난 많이 치기", optionB: "연인 진지하게 대하기", category: "유머" },
    { id: 160, optionA: "연인 귀여워할 때 볼 꼬집기", optionB: "연인 귀여워할 때 머리 쓰다듬기", category: "유머" },

    // === 음식 ===
    { id: 161, optionA: "연인이 만든 간장밥", optionB: "맛집 스테이크", category: "음식" },
    { id: 162, optionA: "짜장면", optionB: "짬뽕", category: "음식" },
    { id: 163, optionA: "치킨", optionB: "피자", category: "음식" },
    { id: 164, optionA: "떡볶이", optionB: "순대", category: "음식" },
    { id: 165, optionA: "삼겹살", optionB: "차돌박이", category: "음식" },
    { id: 166, optionA: "초밥", optionB: "회", category: "음식" },
    { id: 167, optionA: "부침개", optionB: "전", category: "음식" },
    { id: 168, optionA: "라면", optionB: "우동", category: "음식" },
    { id: 169, optionA: "김밥", optionB: "주먹밥", category: "음식" },
    { id: 170, optionA: "붕어빵 팥 먼저", optionB: "붕어빵 머리 먼저", category: "음식" },
    { id: 171, optionA: "민초 좋아", optionB: "민초 싫어", category: "음식" },
    { id: 172, optionA: "파인애플 피자 OK", optionB: "파인애플 피자 NO", category: "음식" },
    { id: 173, optionA: "곱창", optionB: "막창", category: "음식" },
    { id: 174, optionA: "족발", optionB: "보쌈", category: "음식" },
    { id: 175, optionA: "짜파게티", optionB: "너구리", category: "음식" },
    { id: 176, optionA: "연인과 매운 음식 대결", optionB: "연인과 빨리 먹기 대결", category: "음식" },
    { id: 177, optionA: "커피", optionB: "녹차", category: "음식" },
    { id: 178, optionA: "케이크", optionB: "마카롱", category: "음식" },
    { id: 179, optionA: "탕수육 찍먹", optionB: "탕수육 부먹", category: "음식" },
    { id: 180, optionA: "소주", optionB: "맥주", category: "음식" },

    // === 여행 ===
    { id: 181, optionA: "빡센 여행", optionB: "느긋한 여행", category: "여행" },
    { id: 182, optionA: "유명 관광지", optionB: "숨은 명소", category: "여행" },
    { id: 183, optionA: "비행기 여행", optionB: "기차 여행", category: "여행" },
    { id: 184, optionA: "패키지 여행", optionB: "자유 여행", category: "여행" },
    { id: 185, optionA: "여행지 맛집 탐방", optionB: "여행지 풍경 감상", category: "여행" },
    { id: 186, optionA: "해외 여행", optionB: "국내 여행", category: "여행" },
    { id: 187, optionA: "여름 해변", optionB: "겨울 스키장", category: "여행" },
    { id: 188, optionA: "온천 여행", optionB: "스파 여행", category: "여행" },
    { id: 189, optionA: "캠핑장 숙박", optionB: "펜션 숙박", category: "여행" },
    { id: 190, optionA: "배낭여행", optionB: "럭셔리 여행", category: "여행" },
    { id: 191, optionA: "일본 여행", optionB: "동남아 여행", category: "여행" },
    { id: 192, optionA: "유럽 여행", optionB: "미국 여행", category: "여행" },
    { id: 193, optionA: "섬 여행", optionB: "도시 여행", category: "여행" },
    { id: 194, optionA: "제주도", optionB: "부산", category: "여행" },
    { id: 195, optionA: "강원도", optionB: "전라도", category: "여행" },
    { id: 196, optionA: "여행 중 쇼핑", optionB: "여행 중 체험", category: "여행" },
    { id: 197, optionA: "새벽 비행기", optionB: "밤 비행기", category: "여행" },
    { id: 198, optionA: "여행 사진 많이", optionB: "여행 영상 많이", category: "여행" },
    { id: 199, optionA: "혼자 여행 가 본 연인", optionB: "항상 같이 여행 간 연인", category: "여행" },
    { id: 200, optionA: "2박 3일 여행", optionB: "당일치기 여행", category: "여행" },

    // === 상황 Part 2 ===
    { id: 201, optionA: "연인이 나보다 키 큼", optionB: "연인이 나보다 키 작음", category: "상황" },
    { id: 202, optionA: "연인 생일에 케이크 직접 만들기", optionB: "연인 생일에 맛집 예약하기", category: "상황" },
    { id: 203, optionA: "크리스마스에 둘만 보내기", optionB: "크리스마스에 친구들과 보내기", category: "상황" },
    { id: 204, optionA: "발렌타인데이 초콜릿 직접 만들기", optionB: "발렌타인데이 명품 초콜릿 사기", category: "상황" },
    { id: 205, optionA: "화이트데이 사탕 대신 다른 선물", optionB: "화이트데이 전통적인 사탕", category: "상황" },
    { id: 206, optionA: "연인 생일에 파티 열어주기", optionB: "연인 생일에 둘만의 시간", category: "상황" },
    { id: 207, optionA: "기념일에 편지 쓰기", optionB: "기념일에 영상 만들기", category: "상황" },
    { id: 208, optionA: "100일 선물 비쌈", optionB: "100일 선물 의미 있음", category: "상황" },
    { id: 209, optionA: "연인 아플 때 밤새 간호", optionB: "연인 아플 때 병원 데려가기", category: "상황" },
    { id: 210, optionA: "연인 스트레스 받으면 들어주기", optionB: "연인 스트레스 받으면 해결책 제시", category: "상황" },
    { id: 211, optionA: "연인 실수하면 웃어넘기기", optionB: "연인 실수하면 지적하기", category: "상황" },
    { id: 212, optionA: "연인 새 친구 사귀면 축하하기", optionB: "연인 새 친구에게 경계하기", category: "상황" },
    { id: 213, optionA: "연인 이성 친구 만남 OK", optionB: "연인 이성 친구 만남 NO", category: "상황" },
    { id: 214, optionA: "연인 술 마시면 데리러 가기", optionB: "연인 술 마시면 연락만 하기", category: "상황" },
    { id: 215, optionA: "연인 야근하면 야식 배달", optionB: "연인 야근하면 집에서 기다리기", category: "상황" },
    { id: 216, optionA: "연인 헤어스타일 바꾸면 칭찬", optionB: "연인 헤어스타일 바꾸면 솔직한 평가", category: "상황" },
    { id: 217, optionA: "연인 옷 사줄 때 내 취향", optionB: "연인 옷 사줄 때 연인 취향", category: "상황" },
    { id: 218, optionA: "연인 다이어트하면 응원만", optionB: "연인 다이어트하면 같이 하기", category: "상황" },
    { id: 219, optionA: "연인 운동하면 같이 하기", optionB: "연인 운동하면 기다려주기", category: "상황" },
    { id: 220, optionA: "연인 취미 배워보기", optionB: "연인 취미 응원만 하기", category: "상황" },

    // === 극한 선택 Part 2 ===
    { id: 221, optionA: "연인이 내 최애 캐릭터 싫어함", optionB: "연인이 내 최애 음식 싫어함", category: "극한" },
    { id: 222, optionA: "연인과 평생 한식만", optionB: "연인과 평생 양식만", category: "극한" },
    { id: 223, optionA: "연인이 내 노래 실력 비판", optionB: "연인이 내 춤 실력 비판", category: "극한" },
    { id: 224, optionA: "연인 앞에서 울기", optionB: "연인 몰래 울기", category: "극한" },
    { id: 225, optionA: "연인에게 못 지키는 약속하기", optionB: "연인에게 약속 안 하기", category: "극한" },
    { id: 226, optionA: "연인이 늦잠 1시간", optionB: "연인이 약속 취소", category: "극한" },
    { id: 227, optionA: "연인 SNS에 우리 사진 없음", optionB: "연인 SNS에 내 사진만 올림", category: "극한" },
    { id: 228, optionA: "연인이 기념일 깜빡함", optionB: "연인이 내 생일 깜빡함", category: "극한" },
    { id: 229, optionA: "연인 부모님 앞에서 실수", optionB: "우리 부모님 앞에서 연인 실수", category: "극한" },
    { id: 230, optionA: "연인 친구가 우리 사이 험담", optionB: "내 친구가 연인 험담", category: "극한" },
    { id: 231, optionA: "연인이 내 취미 안 좋아함", optionB: "내가 연인 취미 안 좋아함", category: "극한" },
    { id: 232, optionA: "연인과 영화 취향 완전 다름", optionB: "연인과 음악 취향 완전 다름", category: "극한" },
    { id: 233, optionA: "연인이 나보다 술 잘 마심", optionB: "연인이 나보다 술 못 마심", category: "극한" },
    { id: 234, optionA: "연인이 나보다 게임 잘 함", optionB: "연인이 나보다 운동 잘 함", category: "극한" },
    { id: 235, optionA: "연인 핸드폰 비번 모름", optionB: "연인이 내 핸드폰 비번 모름", category: "극한" },
    { id: 236, optionA: "연인이 나 몰래 전 애인 연락", optionB: "내가 연인 몰래 전 애인 연락", category: "극한" },
    { id: 237, optionA: "연인이 우리 사진 안 찍음", optionB: "연인이 우리 사진 SNS에만 올림", category: "극한" },
    { id: 238, optionA: "연인이 내 친구 이름 헷갈림", optionB: "내가 연인 친구 이름 헷갈림", category: "극한" },
    { id: 239, optionA: "연인 앞에서 다른 이성 칭찬", optionB: "연인이 내 앞에서 다른 이성 칭찬", category: "극한" },
    { id: 240, optionA: "연인과 MBTI 상극", optionB: "연인과 혈액형 궁합 안 맞음", category: "극한" },

    // === 일상 Part 2 ===
    { id: 241, optionA: "연인과 아침 조깅", optionB: "연인과 저녁 산책", category: "일상" },
    { id: 242, optionA: "연인과 같은 이불 덮기", optionB: "연인과 각자 이불 덮기", category: "일상" },
    { id: 243, optionA: "연인과 같은 베개 쓰기", optionB: "연인과 각자 베개 쓰기", category: "일상" },
    { id: 244, optionA: "연인 코골이 참기", optionB: "연인 이갈이 참기", category: "일상" },
    { id: 245, optionA: "연인 잠꼬대 듣기", optionB: "연인 침 흘리며 자기", category: "일상" },
    { id: 246, optionA: "연인과 함께 알람 끄기", optionB: "연인 먼저 일어나서 깨워주기", category: "일상" },
    { id: 247, optionA: "연인 배고플 때 같이 배고프기", optionB: "연인 배고플 때 간식 챙겨주기", category: "일상" },
    { id: 248, optionA: "연인과 같이 욕실 사용", optionB: "연인과 욕실 순서 정해서 사용", category: "일상" },
    { id: 249, optionA: "연인 화장할 때 옆에서 기다리기", optionB: "연인 화장할 때 먼저 준비하기", category: "일상" },
    { id: 250, optionA: "연인과 커플 잠옷 입기", optionB: "연인과 각자 편한 잠옷 입기", category: "일상" },

    // === 연애 Part 2 ===
    { id: 251, optionA: "연인 칭찬 자주 하기", optionB: "연인 칭찬 진심 담아 가끔", category: "연애" },
    { id: 252, optionA: "연인한테 먼저 고백받기", optionB: "연인한테 먼저 고백하기", category: "연애" },
    { id: 253, optionA: "연인과 스킨십 먼저 시작", optionB: "연인이 스킨십 먼저 시작", category: "연애" },
    { id: 254, optionA: "연인과 눈 맞추며 대화", optionB: "연인과 나란히 앉아 대화", category: "연애" },
    { id: 255, optionA: "연인 사진 락스크린으로", optionB: "연인 사진 배경화면으로", category: "연애" },
    { id: 256, optionA: "연인과 커플 반지", optionB: "연인과 커플 팔찌", category: "연애" },
    { id: 257, optionA: "연인과 커플 티 입기", optionB: "연인과 같은 색 옷 입기", category: "연애" },
    { id: 258, optionA: "연인과 같은 음악 듣기", optionB: "연인과 같은 영상 보기", category: "연애" },
    { id: 259, optionA: "연인과 함께 운동", optionB: "연인과 함께 독서", category: "연애" },
    { id: 260, optionA: "연인에게 러브레터 쓰기", optionB: "연인에게 노래 불러주기", category: "연애" },

    // === 가치관 Part 2 ===
    { id: 261, optionA: "미래 계획 세우는 연인", optionB: "현재에 충실한 연인", category: "가치관" },
    { id: 262, optionA: "감정 표현 잘하는 연인", optionB: "행동으로 보여주는 연인", category: "가치관" },
    { id: 263, optionA: "논리적인 연인", optionB: "감성적인 연인", category: "가치관" },
    { id: 264, optionA: "야망 있는 연인", optionB: "소박한 연인", category: "가치관" },
    { id: 265, optionA: "정리정돈 잘하는 연인", optionB: "창의적이지만 어지러운 연인", category: "가치관" },
    { id: 266, optionA: "아끼고 모으는 연인", optionB: "경험에 투자하는 연인", category: "가치관" },
    { id: 267, optionA: "계획대로 움직이는 연인", optionB: "상황에 따라 움직이는 연인", category: "가치관" },
    { id: 268, optionA: "혼자 있는 시간 필요한 연인", optionB: "항상 같이 있고 싶은 연인", category: "가치관" },
    { id: 269, optionA: "말로 사랑 표현하는 연인", optionB: "선물로 사랑 표현하는 연인", category: "가치관" },
    { id: 270, optionA: "시간 잘 지키는 연인", optionB: "가끔 늦지만 꼼꼼한 연인", category: "가치관" },

    // === 취향 Part 2 ===
    { id: 271, optionA: "매일 새로운 메뉴", optionB: "매일 같은 메뉴", category: "취향" },
    { id: 272, optionA: "연인과 맵찔이", optionB: "연인과 맵부심", category: "취향" },
    { id: 273, optionA: "연인과 단짠단짠", optionB: "연인과 담백하게", category: "취향" },
    { id: 274, optionA: "연인과 새벽 편의점", optionB: "연인과 새벽 드라이브", category: "취향" },
    { id: 275, optionA: "연인과 인생네컷", optionB: "연인과 포토이즘", category: "취향" },
    { id: 276, optionA: "연인과 노래방", optionB: "연인과 방탈출", category: "취향" },
    { id: 277, optionA: "연인과 보드게임", optionB: "연인과 콘솔게임", category: "취향" },
    { id: 278, optionA: "연인과 등산", optionB: "연인과 수영", category: "취향" },
    { id: 279, optionA: "연인과 공포영화", optionB: "연인과 코미디영화", category: "취향" },
    { id: 280, optionA: "연인과 웹툰 보기", optionB: "연인과 드라마 보기", category: "취향" },

    // === 재미 ===
    { id: 281, optionA: "연인이 나 닮은꼴", optionB: "연인이 연예인 닮은꼴", category: "재미" },
    { id: 282, optionA: "연인이 내 팬", optionB: "내가 연인 팬", category: "재미" },
    { id: 283, optionA: "연인이 나 그린 그림", optionB: "연인이 나 찍은 사진", category: "재미" },
    { id: 284, optionA: "연인이 나한테 랩하기", optionB: "연인이 나한테 댄스하기", category: "재미" },
    { id: 285, optionA: "연인과 틱톡 챌린지", optionB: "연인과 유튜브 브이로그", category: "재미" },
    { id: 286, optionA: "연인 목소리 ASMR", optionB: "연인 목소리 알람", category: "재미" },
    { id: 287, optionA: "연인이 개그맨처럼", optionB: "연인이 배우처럼", category: "재미" },
    { id: 288, optionA: "연인과 댄스 배우기", optionB: "연인과 요리 배우기", category: "재미" },
    { id: 289, optionA: "연인과 악기 배우기", optionB: "연인과 그림 배우기", category: "재미" },
    { id: 290, optionA: "연인과 셀카 장인", optionB: "연인과 풍경 장인", category: "재미" },

    // === 마무리 ===
    { id: 291, optionA: "연인과 오래 연애 후 결혼", optionB: "연인과 빠르게 결혼", category: "미래" },
    { id: 292, optionA: "연인과 함께 늙어가기", optionB: "연인과 영원히 젊게 살기", category: "미래" },
    { id: 293, optionA: "연인과 첫사랑", optionB: "연인과 마지막 사랑", category: "가치관" },
    { id: 294, optionA: "연인이 내 전부", optionB: "연인이 내 일부", category: "가치관" },
    { id: 295, optionA: "운명적인 만남", optionB: "노력으로 이어진 만남", category: "가치관" },
    { id: 296, optionA: "연인과 매일 싸우고 화해", optionB: "연인과 한 달에 한 번 크게 싸우기", category: "상황" },
    { id: 297, optionA: "연인과 비밀 없이", optionB: "연인과 비밀 하나씩", category: "가치관" },
    { id: 298, optionA: "연인에게 모든 걸 공유", optionB: "연인에게 필요한 것만 공유", category: "가치관" },
    { id: 299, optionA: "사랑은 변하는 것", optionB: "사랑은 변하지 않는 것", category: "가치관" },
    { id: 300, optionA: "연인과 평생 연애하기", optionB: "연인과 결혼해서 가족 되기", category: "미래" },

    // === 추가 질문들 ===
    { id: 301, optionA: "연인 잠버릇 사진 찍기", optionB: "연인 잠버릇 영상 찍기", category: "유머" },
    { id: 302, optionA: "연인과 쌍둥이 코디", optionB: "연인과 정반대 코디", category: "취향" },
    { id: 303, optionA: "연인이 나 놀리기", optionB: "내가 연인 놀리기", category: "유머" },
    { id: 304, optionA: "연인과 웃기 대결", optionB: "연인과 진지 대결", category: "유머" },
    { id: 305, optionA: "연인이 나 무서워하기", optionB: "내가 연인 무서워하기", category: "유머" },
    { id: 306, optionA: "연인과 같이 울기", optionB: "연인과 같이 웃기", category: "감정" },
    { id: 307, optionA: "연인이 날 위해 눈물 흘리기", optionB: "내가 연인 위해 눈물 흘리기", category: "감정" },
    { id: 308, optionA: "연인과 추억의 노래", optionB: "연인과 추억의 장소", category: "추억" },
    { id: 309, optionA: "연인의 꿈 응원하기", optionB: "연인과 같은 꿈 꾸기", category: "가치관" },
    { id: 310, optionA: "연인과 행복한 현재", optionB: "연인과 희망찬 미래", category: "가치관" },
];

// 오늘의 질문 가져오기 (완료된 질문 제외)
export const getTodayQuestion = (completedIds = []) => {
    const availableQuestions = BALANCE_QUESTIONS.filter(q => !completedIds.includes(q.id));
    if (availableQuestions.length === 0) {
        // 모든 질문을 다 했으면 다시 처음부터
        return BALANCE_QUESTIONS[0];
    }
    // 날짜 기반 선택 (같은 날엔 같은 질문)
    const today = new Date().toISOString().slice(0, 10);
    const seed = today.split('-').reduce((a, b) => a + parseInt(b), 0);
    const index = seed % availableQuestions.length;
    return availableQuestions[index];
};
